apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website     # name in argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/<YOUR_NAME_HERE>/rancher-desktop-playground'
    path: website/overlays/localdev # path to overlay with kustomization.yaml
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo  # namespace to create the website resources in
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true